In [48]:
# RFM ile müşteri segmentasyonu
# RFM: Recency, Frequency, Monetary
# Recency: Son alışveriş tarihine göre müşteri segmentasyonu
# Frequency: Müşterinin alışveriş sıklığına göre segmentasyonu
# Monetary: Müşterinin harcama miktarına göre segmentasyonu

In [49]:
# 1. iş problemi (Business Problem)
# 2. veriyi anlama (Data Understanding)
# 3. veriyi hazırlama (Data Preparation)
# 4. RFM Metriklerini Hesaplama  (calculate RFM metrics)
# 5. RFM Skorlarını Hesaplama (calculate RFM scores)
# 6. RFM segmentlerinin oluşturulması ve analiz edilmesi (create and analyze RFM segments)
# 7. Tüm sürecin fonksiyonlaştırılması (functionalization of the entire process)

In [50]:
# 1. İŞ PROBLEMİ
# Bir e-ticaret şirketi, müşteri segmentasyonu yaparak pazarlama stratejilerini geliştirmek istiyor.

In [51]:
#kütüphaneler
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [53]:
df_ = pd.read_excel("Kurs Materyalleri(CRM Analitiği)\datasets\online_retail_II.xlsx")
df = df_.copy()
df.head()

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00  6.950    13085.000  United Kingdom
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00  2.100    13085.000  United Kingdom
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom

In [54]:
df.shape

(525461, 8)

In [55]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [56]:
df["Description"].nunique() #ürün sayısı

4681

In [57]:
df["Description"].value_counts().head(10) #en çok satılan ürünler

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
60 TEATIME FAIRY CAKE CASES           1400
HOME BUILDING BLOCK WORD              1386
JUMBO BAG RED RETROSPOT               1310
LUNCH BAG RED SPOTTY                  1274
REX CASH+CARRY JUMBO SHOPPER          1232
Name: count, dtype: int64

In [58]:
df.groupby("Description").agg({"Quantity": "sum"}).sort_values("Quantity", ascending=False).head(10) #ürün bazında satış miktarları

                                    Quantity
Description
WHITE HANGING HEART T-LIGHT HOLDER     57733
WORLD WAR 2 GLIDERS ASSTD DESIGNS      54698
BROCADE RING PURSE                     47647
PACK OF 72 RETRO SPOT CAKE CASES       46106
ASSORTED COLOUR BIRD ORNAMENT          44925
60 TEATIME FAIRY CAKE CASES            36326
PACK OF 60 PINK PAISLEY CAKE CASES     31822
JUMBO BAG RED RETROSPOT                30727
SMALL POPCORN HOLDER                   29500
STRAWBERRY CERAMIC TRINKET BOX         26563

In [59]:
df["Invoice"].nunique() #fatura sayısı

28816

In [60]:
df["Total_price"] = df["Quantity"] * df["Price"]

In [61]:
df.head()

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country  Total_price
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00  6.950    13085.000  United Kingdom       83.400
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00  2.100    13085.000  United Kingdom      100.800
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom       30.000

In [62]:
df.groupby("Invoice").agg({"Total_price": "sum"}).sort_values("Total_price", ascending=False).head(10) #fatura bazında toplam satış fiyatları

         Total_price
Invoice
533027     49844.990
531516     45332.970
493819     44051.600
524181     33167.800
526934     26007.080
512771     25111.090
515944     22863.360
503061     22853.770
517731     21984.000
495591     18570.880

In [63]:
df["Invoice"].nunique() #fatura sayısı

28816

In [64]:
###############################################################
# 3. Veri Hazırlama (Data Preparation)
###############################################################

In [65]:
df.shape

(525461, 9)

In [66]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
Total_price         0
dtype: int64

In [67]:
df.dropna(inplace=True) # eksik verileri sil
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Total_price    0
dtype: int64

In [68]:
df.shape

(417534, 9)

In [69]:
df.describe().T

                 count                           mean                  min                  25%                  50%                  75%                  max      std
Quantity    417534.000                         12.759            -9360.000                2.000                4.000               12.000            19152.000  101.220
InvoiceDate     417534  2010-07-01 01:12:19.787609856  2009-12-01 07:45:00  2010-03-26 11:26:00  2010-07-08 19:12:00  2010-10-14 14:08:00  2010-12-09 20:01:00      NaN
Price       417534.000                          3.888                0.000                1.250                1.950                3.750            25111.090   71.132
Customer ID 417534.000                      15360.645            12346.000            13983.000            15311.000            16799.000            18287.000 1680.811
Total_price 417534.000                         19.994           -25111.090                4.250               11.250               19.350            15818.400   99.916

In [70]:
df = df[~df["Invoice"].str.contains("C", na=False)] #C ile başlayan faturaları sil

In [71]:
df.shape

(407695, 9)

In [72]:
###############################################################
# 4. RFM Metriklerinin Hesaplanması (Calculating RFM Metrics)
###############################################################

In [73]:
# Recency, Frequency, Monetary
df.head()

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country  Total_price
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00  6.950    13085.000  United Kingdom       83.400
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00  2.100    13085.000  United Kingdom      100.800
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom       30.000

In [74]:
df["InvoiceDate"].max() #son alışveriş tarihi

Timestamp('2010-12-09 20:01:00')

In [75]:
df["InvoiceDate"].min() #ilk alışveriş tarihi

Timestamp('2009-12-01 07:45:00')

In [76]:
df["InvoiceDate"].nunique() #farklı tarih sayısı

18010

In [77]:
df.head()

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country  Total_price
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00  6.950    13085.000  United Kingdom       83.400
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00  2.100    13085.000  United Kingdom      100.800
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom       30.000

In [78]:
today_date = dt.datetime(2010, 12, 11) #bugünün tarihi

In [79]:
df["Recency"] = (today_date - df["InvoiceDate"]).dt.days

In [80]:
df["Frequency"] = df["Invoice"].nunique()

In [81]:
df["Monetary"] = df["Total_price"]

In [82]:
df.head(10)

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country  Total_price  Recency  Frequency  Monetary
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00  6.950    13085.000  United Kingdom       83.400      374      19215    83.400
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000      374      19215    81.000
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00  6.750    13085.000  United Kingdom       81.000      374      19215    81.000
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00  2.100    13085.000  United Kingdom      100.800      374      19215   100.800
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom       30.000      374      19215    30.000
5  489434     22064           PINK DOUGHNUT TRINKET POT         24 2009-12-01 07:45:00  1.650    13085.000  United Kingdom       39.600      374      19215    39.600
6  489434     21871                  SAVE THE PLANET MUG        24 2009-12-01 07:45:00  1.250    13085.000  United Kingdom       30.000      374      19215    30.000
7  489434     21523   FANCY FONT HOME SWEET HOME DOORMAT        10 2009-12-01 07:45:00  5.950    13085.000  United Kingdom       59.500      374      19215    59.500
8  489435     22350                            CAT BOWL         12 2009-12-01 07:46:00  2.550    13085.000  United Kingdom       30.600      374      19215    30.600
9  489435     22349       DOG BOWL , CHASING BALL DESIGN        12 2009-12-01 07:46:00  3.750    13085.000  United Kingdom       45.000      374      19215    45.000

In [83]:
print("Top 10 Recency:")
print(df["Customer ID"].groupby(df["Recency"]).count().sort_values(ascending=False).head(10)) 

print("\nTop 10 Frequency:")
print(df["Customer ID"].groupby(df["Frequency"]).count().sort_values(ascending=False).head(10))

print("\nTop 10 Monetary:")
print(df["Customer ID"].groupby(df["Monetary"]).count().sort_values(ascending=False).head(10))

Top 10 Recency:
Recency
19    3248
36    3023
15    2989
64    2843
33    2787
30    2750
26    2732
29    2715
5     2708
17    2687
Name: Customer ID, dtype: int64

Top 10 Frequency:
Frequency
19215    407695
Name: Customer ID, dtype: int64

Top 10 Monetary:
Monetary
15.000    20122
17.700    11869
10.200    11361
1.250      8961
3.750      8886
2.950      8137
7.500      7225
19.800     6659
2.500      6069
1.650      5993
Name: Customer ID, dtype: int64